title: Mario Bianchi
description: M.Sc. student in Data Science and Business Informatics at Università di Pisa. \nGraduate in Economics and Management at LUISS Guido Carli.
theme: jekyll-theme-minimal
