title: Mario Bianchi
description: Master's Degree in Data Science and Business Informatics at Università di Pisa.
info: Bachelor's Degree in Economics and Management at LUISS Guido Carli.
theme: jekyll-theme-minimal
